name: flutter_notes
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.3.1
  get: ^4.6.1
  intl: ^0.17.0
  shared_preferences: ^2.0.13
  flutter_staggered_grid_view: ^0.6.1
  flutter_native_splash: ^2.1.6

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
